# -*- coding: utf-8 -*-
"""scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uh1x1VZ4YWTybmQKcRpU6E2EBxdMzDt1
"""

import requests
from bs4 import BeautifulSoup

with open('House_prise.txt','w',encoding='utf-8') as file:
    lien = "https://www.ouedkniss.com/immobilier/vente/"
    '''file.write(
        'Numéro' + ',' + 'Nombre de vues' + ',' + 'Déposée le' + ',' + 'Quartier' + ',' + 'Nombre de pièces' + ',' + 'Nombre d\'étages' + ',' + ',' + 'Superficie ' + ','
        + 'Spéc' + ',' + 'Spéc2' + ',' + 'Spéc3' + ',' + 'Spéc4' + ',' + 'Spéc5' + ',' + 'Spéc6' + ',' + 'Spéc7\n')'''
    for i in range(0,200):
        response = requests.get(lien+str(i))
        bsoup = BeautifulSoup(response.text,"lxml")
        #print(soup)
        annonce = bsoup.find_all('div' , attrs={'class' : 'annonce_buttons'})
        #print(annonce[0])
        for elm in annonce:
            link = elm.find('a' , attrs={'class' : 'button button_details'})['href']
            print(link)
            # https://www.ouedkniss.com/vente-appartement-f2-alger-el-biar-algerie-immobilier-d24432899?utm_medium=listing
            response = requests.get('https://www.ouedkniss.com/'+link)
            soup = BeautifulSoup(response.text, "lxml")
            annonce = str(soup.find_all('span', attrs={'class': 'description_span'})).replace(
                '<span class="description_span" itemprop="productID">', '').replace('</span>', '').replace(
                '<span class="description_span">', '',).replace('[','').replace(']','')
            #aa = annonce.split(',')
            file.write(annonce+ '\n')
            #print(annonce)

